services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt -f https://download.pytorch.org/whl/cpu
    startCommand: gunicorn main:app --timeout 120
