services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
    startCommand: gunicorn main:app --timeout 120
